# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  init:
    mode: never
  jpa:
    show-sql: true
    open-in-view: false

    # validate db by model // update
    hibernate:
      ddl-auto: update


    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5444/dent-alma
    username: Alma
    password: alma123

  docker:
    compose:
      enabled: false

