version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: true_false_db
    restart: always
    environment:
      POSTGRES_USER: BrendaBecerra
      POSTGRES_PASSWORD: libeib
      POSTGRES_DB: true_false_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: